[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
evm_version = 'cancun'
optimizer = true
optimizer_runs = 450

[rpc_endpoints]
blast = "${BLAST_RPC}"
optimism = "${OPTIMISM_RPC}"
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"
ethereum = "${ETHEREUM_RPC}"
avalanche = "${AVALANCHE_RPC}"
metis = "${METIS_RPC}"
sonic = "${SONIC_RPC}"
bsc = "${BSC_RPC}"
scroll = "${SCROLL_RPC}"
mode = "${MODE_RPC}"
b2 = "${B2_RPC}"
unichain = "${UNICHAIN_RPC}"
zksync = "${ZKSYNC_RPC}"
core = "${CORE_RPC}"